extends:
  - eslint:recommended
  - google

parserOptions:
  ecmaVersion: 6
  sourceType: module

rules:
  max-len:
    - error
    - code: 120
  require-jsdoc:
    - error
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
        ArrowFunctionExpression: true
        FunctionExpression: true
  valid-jsdoc:
    - error
    - prefer:
        arg: param
        argument: param
        constructor: class
        return: returns
        virtual: abstract
      preferType:
        Number: number
        String: string
        Boolean: boolean
      requireReturn: true
      requireReturnType: true
      requireParamDescription: false
      requireReturnDescription: false
      requireParamType: true

globals:
  document: true
  window: true
  console: true
